version: '3'
services:
  jekyll:
    image: jekyll/jekyll:3.5
    volumes:
      - ./jekyll:/srv/jekyll
      - "webpack-bundle:/srv/bundle"
    command: jekyll serve
    env_file: ${ENV_FILE:-default.env}
    ports:
      - "4000:4000"
  webpack:
      image: node:8.1
      working_dir: /usr/src/app
      command: yarn run watch
      env_file: ${ENV_FILE:-default.env}
      volumes:
          - "./webpack:/usr/src/app"
          - "webpack-bundle:/usr/src/app/bundle"
  api:
      build: ./api
      image: dockerregenx_api:latest
      environment:
        - ENABLE_CORS=1
      ports:
        - "4001:4001"
      volumes:
          - "./api:/usr/src/app"

volumes:
  webpack-bundle:
