version: '3'
services:
  jekyll:
    image: jekyll/jekyll:3.5
    volumes:
      - ./jekyll:/srv/jekyll
      - "webpack-bundle:/srv/bundle"
    command: jekyll serve
    environment:
      - JEKYLL_ENV=development
      - JKL__url=http://localhost:4000
    ports:
      - "4000:4000"
  webpack:
      image: node:8.1
      working_dir: /usr/src/app
      command: yarn run watch
      environment:
        - NODE_ENV=development
        - API_URL=http://localhost:4001/api
      volumes:
          - "./webpack:/usr/src/app"
          - "webpack-bundle:/usr/src/app/bundle"
  api:
      build: ./api
      environment:
        - ENABLE_CORS=1
      ports:
        - "4001:4001"
      volumes:
          - "./api:/usr/src/app"

volumes:
  webpack-bundle:
