title: Your awesome title
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog

# Ink settings
ink:
  load_fontawesome: true
  load_js: false

# Build settings
markdown: kramdown

# Settings from environment:
# All env variables prefixed with 'JKL__' will be resolved to another configuration
# See ./_plugins/environment_variables.rb
